FROM networkml
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

RUN pip3 install --no-cache-dir -r test-requirements.txt
ENTRYPOINT ["pytest"]
CMD ["-l", "-s", "-v", "-n2", "--cov=tests/", "--cov=networkml/", "--cov-report", "term-missing", "-c", ".coveragerc"]
