FROM cyberreboot/poseidonml:base
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

ENV PYTHONPATH=/poseidonml/utils:$PYTHONPATH
ENV PYTHONPATH=/poseidonml/DeviceClassifier:$PYTHONPATH

COPY tests/test_labels.json /test_labels.json

ENTRYPOINT ["pytest"]
CMD ["-l", "-s", "-v", "--cov=tests/", "--cov=utils/", "--cov=DeviceClassifier/", "--cov-report", "term-missing"]
