FROM cyberreboot/poseidonml:base
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

ENV PYTHONPATH=/poseidonml/utils:$PYTHONPATH
ENV PYTHONPATH=/poseidonml/DeviceClassifier:$PYTHONPATH

ENTRYPOINT ["pytest"]
CMD ["-l", "-s", "-v", "--cov=.", "--cov-report", "term-missing"]
