#!/bin/sh

arg1=$1
arg2=$2

if [ "$arg1" = "onelayer" ]
then
	model_choice="_OneLayer.py"
elif [ "$arg1" = "randomforest" ]
then
	model_choice="_RandomForest.py"
else
	echo "Invalid model choice, choose 'onelayer' or 'randomforest'"
	exit 1
fi

if [ "$arg2" = "train" ]
then
	cmd=$arg2$model_choice
elif [ "$arg2" = "eval" ]
then
	cmd=$arg2$model_choice
elif [ "$arg2" = "testing" ]
then
	cmd=$arg2$model_choice
else
	echo "Invalid runtime choice, choose 'train', 'eval', or 'testing'"
	exit 1
fi

cd ../NodeClassifier
python3 $cmd
