FROM python:3.5
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"

RUN apt-get update && apt-get install -y \
    tcpdump

RUN pip install numpy scikit-learn==0.18.2 scipy
COPY . /TraditionalML
WORKDIR /TraditionalML

ENTRYPOINT ["python3.5", "train_RandomForest.py"]
CMD [""]
