name: secrets

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: scan
      run: |
        export DEBIAN_FRONTEND=noninteractive && \
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections && \
        sudo apt-get update && \
        sudo apt-get install -yq --no-install-recommends python3-wheel python3.9 python3.9-dev python3-setuptools dialog apt-utils tshark jq && \
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2 && \
        python3 -m pip install --upgrade pip && \
        pip3 install whispers && \
        mkdir /reports/ && \
        whispers --severity BLOCKER,CRITICAL -o /reports/whispers.json ${GITHUB_WORKSPACE} && \
        echo "::set-output name=found-count::$(wc -l /reports/whispers.json | cut -d' ' -f1)"
    - name: Upload scan reports
      uses: actions/upload-artifact@v2.3.1
      with:
        name: whispers-report
        path: /reports/whispers.json
    - name: Fail if found
      if: ${{steps.scan.outputs.found-count}} != 0
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Secrets found. Please check the uploaded report')